### ISSUE TITLE
Send rate is not the value I set

### ISSUE THREAD

**Issue by Bear-hub** [hyperledger-caliper/caliper#1188]
## Context

When I set the fixed-rate to 200 TPS, the actual fixed-rate is more than 600 TPS. This problem occurs when the log reports a timeout error. So I have two questions in total, one is how to determine the maximum TPS of different contracts, the other is when the timeout error will occur, and whether the TPS measured in the background of the timeout error is accurate.

## Actual Behavior

`myAssetBenchmark.yaml`
```
test:
    name: basic-contract-benchmark
    description: test benchmark
    workers:
      type: local
      number: 2
    rounds:
      - label: updateIot
        description: Update asset benchmark
        txDuration: 30
        rateControl:
          type: fixed-rate
          opts:
            tps: 200
        workload:
          module: workload/updateIot.js
          arguments:
            assets: 5
            contractId: iot
monitors:
  resource:
  - module: docker
    options:
      interval: 5 
      containers:
      - all
```

## Context

I have two questions in total, one is how to determine the maximum TPS of different contracts, the other is when the timeout error will occur, and whether the TPS measured in the background of the timeout error is accurate.
## Your Environment

* Version used:0.4.2
* Platform: Hyperledger Fabric Version 2.2

**Comment by davidkel** [comment]
So you are saying that it achieves the specified tps value if no timeout error occurs ? but if you get a timeout then the reported tps is wrong ? Can you provide more details, such as the report output showing the issue with the associated benchmark file and the actual errors being reported. The rate controller manages the rate based on actual submissions so shouldn't be distinguishing between submissions that subsequently fail vs ones that pass

**Comment by Bear-hub** [comment]
> 所以你是说，如果没有发生超时错误，它就会达到指定的tps值？但是，如果您得到超时，那么报告的tps是错误的吗？您能否提供更多详细信息，例如显示关联基准文件问题的报告输出以及报告的实际错误。速率控制器根据实际提交来管理速率，因此不应区分随后失败的提交与通过的提交



> So you are saying that it achieves the specified tps value if no timeout error occurs ? but if you get a timeout then the reported tps is wrong ? Can you provide more details, such as the report output showing the issue with the associated benchmark file and the actual errors being reported. The rate controller manages the rate based on actual submissions so shouldn't be distinguishing between submissions that subsequently fail vs ones that pass

![1651656062(1)](https://user-images.githubusercontent.com/71493973/166655909-f4e421eb-6e06-4211-a9f2-11176a3e07f0.jpg)


> So you are saying that it achieves the specified tps value if no timeout error occurs ? but if you get a timeout then the reported tps is wrong ? Can you provide more details, such as the report output showing the issue with the associated benchmark file and the actual errors being reported. The rate controller manages the rate based on actual submissions so shouldn't be distinguishing between submissions that subsequently fail vs ones that pass

Hi, I recently encountered this problem again. The sending rate is always not the value I set. I set the sending rate to 50TPS, but in the actual measured results, the sending rate is 70TPS. There is no error log in the whole process, which is really difficult to understand. I hope you can reply.

**Comment by Bear-hub** [comment]
> So you are saying that it achieves the specified tps value if no timeout error occurs ? but if you get a timeout then the reported tps is wrong ? Can you provide more details, such as the report output showing the issue with the associated benchmark file and the actual errors being reported. The rate controller manages the rate based on actual submissions so shouldn't be distinguishing between submissions that subsequently fail vs ones that pass

Hi, I recently encountered this problem again. The sending rate is always not the value I set. I set the sending rate to 50TPS, but in the actual measured results, the sending rate is 70TPS. There is no error log in the whole process, which is really difficult to understand. I hope you can reply

**Comment by Bear-hub** [comment]
`test:
    name: basic-contract-benchmark
    description: test benchmark
    workers:
      type: local
      number: 1
    rounds:
      - label: logisticsUpload
        description: Read asset benchmark
#        txDuration: 30
        txNumber: 1000
        rateControl:
          type: fixed-load
          opts:
            tps: 50
        workload:
          module: workload/logisticsUpload.js
          arguments:
            assets: 3
            contractId: logistics
      - label: logisticsUpDate
        description: Read asset benchmark
#        txDuration: 30
        txNumber: 1000
        rateControl:
          type: fixed-load
          opts:
#            transactionLoad: 50
            tps: 50
        workload:
          module: workload/logisticsUpDate.js
          arguments:
            assets: 3
            contractId: logistics
      - label: logisticsInquiry
        description: Read asset benchmark
#        txDuration: 30
        txNumber: 1000
        rateControl:
          type: fixed-load
          opts:
            tps: 50
        workload:
          module: workload/logisticsInquiry.js
          arguments:
            assets: 3
            contractId: logistics
monitors:
  resource:
    - module: docker
      options:
        interval: 5
        containers:
          - all`

**Comment by Bear-hub** [comment]
`test:
    name: basic-contract-benchmark
    description: test benchmark
    workers:
      type: local
      number: 1
    rounds:
      - label: logisticsUpload
        description: Read asset benchmark
        txNumber: 1000
        rateControl:
          type: fixed-load
          opts:
            tps: 50
        workload:
          module: workload/logisticsUpload.js
          arguments:
            assets: 3
            contractId: logistics
      - label: logisticsUpDate
        description: Read asset benchmark
        txNumber: 1000
        rateControl:
          type: fixed-load
          opts:
            tps: 50
        workload:
          module: workload/logisticsUpDate.js
          arguments:
            assets: 3
            contractId: logistics
      - label: logisticsInquiry
        description: Read asset benchmark
        txNumber: 1000
        rateControl:
          type: fixed-load
          opts:
            tps: 50
        workload:
          module: workload/logisticsInquiry.js
          arguments:
            assets: 3
            contractId: logistics
monitors:
  resource:
    - module: docker
      options:
        interval: 5
        containers:
          - all`

**Comment by Bear-hub** [comment]
test:
    name: basic-contract-benchmark
    description: test benchmark
    workers:
      type: local
      number: 2
    rounds:
      - label: updateIot
        description: Update asset benchmark
        txDuration: 30
        rateControl:
          type: fixed-rate
          opts:
            tps: 200
        workload:
          module: workload/updateIot.js
          arguments:
            assets: 5
            contractId: iot
monitors:
  resource:
  - module: docker
    options:
      interval: 5 
      containers:
      - all

**Comment by Bear-hub** [comment]
```
test:
    name: basic-contract-benchmark
    description: test benchmark
    workers:
      type: local
      number: 1
    rounds:
      - label: logisticsUpload
        description: Read asset benchmark
        txNumber: 1000
        rateControl:
          type: fixed-load
          opts:
            tps: 50
        workload:
          module: workload/logisticsUpload.js
          arguments:
            assets: 3
            contractId: logistics
      - label: logisticsUpDate
        description: Read asset benchmark
        txNumber: 1000
        rateControl:
          type: fixed-load
          opts:
            tps: 50
        workload:
          module: workload/logisticsUpDate.js
          arguments:
            assets: 3
            contractId: logistics
      - label: logisticsInquiry
        description: Read asset benchmark
        txNumber: 1000
        rateControl:
          type: fixed-load
          opts:
            tps: 50
        workload:
          module: workload/logisticsInquiry.js
          arguments:
            assets: 3
            contractId: logistics
monitors:
  resource:
    - module: docker
      options:
        interval: 5
        containers:
          - all
```
