### ISSUE TITLE
Send rate is not the value I set!!!

### ISSUE THREAD

**Issue by luodeyu** [hyperledger-caliper/caliper#1392]
### Which Caliper version are you using?

v0.5.0

### Which Node.JS version are you using?

v16

### Which operating system are you using?

ubuntu 18.04

### Please provide some context for your error. For example, when did the error occur? What were you trying to achieve, and how?

When fixed-rate greater than ablout 1400tps, the real send rate is not equal to the "fixed-rate" I set. 

### What was the observed incorrect behavior?

| Name      | Succ   | Fail | Send Rate (TPS) | Max Latency (s) | Min Latency (s) | Avg Latency (s) | Throughput (TPS) |
|-----------|--------|------|-----------------|-----------------|-----------------|-----------------|------------------|
| readAsset | 163691 | 0    | 1634.3          | 0.26            | 0.00            | 0.04            | 1634.2           |

### Please provide the error logs and their surroundings.

```text
no
```

### Please provide your benchmark configuration file content, if possible.

```yaml
test:
    name: basic-contract-benchmark
    description: test benchmark
    workers:
      number: 10
    rounds:
      - label: readAsset
        description: Read asset benchmark
        txDuration: 100
        rateControl:
          type: fixed-rate
          opts:
            tps: 2000
        workload:
          module: workload/readAsset.js
          arguments:
            assets: 30
            contractId: basic
```

### Please provide your network configuration file content, if possible.

```yaml
name: Calier test
version: "2.0.0"

caliper:
  blockchain: fabric

channels:
  - channelName: mychannel
    contracts:
    - id: basic

organizations:
  - mspid: Org1MSP
    identities:
      certificates:
      - name: 'User1'
        clientPrivateKey:
          path: '../fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/priv_sk'
        clientSignedCert:
          path: '../fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/User1@org1.example.com-cert.pem'
    connectionProfile:
      path: '../fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/connection-org1.yaml'
      discover: true
```

### Please provide your workload module content, if possible.

```nodejs
just the simple readAsset.js
```
